#!/usr/bin/env python3
"""
Compare enhanced PPTX files generated by python-pptx and ppt-rs.
This compares the versions with slides for better alignment testing.
"""

import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path
import difflib
import sys

def extract_pptx_contents(pptx_path):
    """Extract all XML files from PPTX."""
    contents = {}
    try:
        with zipfile.ZipFile(pptx_path, 'r') as z:
            for name in z.namelist():
                if name.endswith('.xml'):
                    contents[name] = z.read(name).decode('utf-8')
    except Exception as e:
        print(f"Error extracting {pptx_path}: {e}")
    return contents

def compare_files(file1_path, file2_path):
    """Compare two PPTX files."""
    print(f"\n{'='*80}")
    print(f"Comparing Enhanced PPTX Files (with Slides)")
    print(f"{'='*80}")
    print(f"File 1 (Reference): {file1_path}")
    print(f"File 2 (ppt-rs):    {file2_path}")
    
    # Extract contents
    print("\nExtracting XML files...")
    contents1 = extract_pptx_contents(file1_path)
    contents2 = extract_pptx_contents(file2_path)
    
    print(f"  File 1: {len(contents1)} XML files")
    print(f"  File 2: {len(contents2)} XML files")
    
    # Get all unique files
    all_files = set(contents1.keys()) | set(contents2.keys())
    
    # Compare each file
    differences = {}
    for filename in sorted(all_files):
        xml1 = contents1.get(filename, "")
        xml2 = contents2.get(filename, "")
        
        if xml1 != xml2:
            differences[filename] = (xml1, xml2)
    
    # Report results
    print(f"\n{'='*80}")
    print(f"Comparison Results")
    print(f"{'='*80}")
    print(f"Total XML files: {len(all_files)}")
    print(f"Matching files: {len(all_files) - len(differences)}")
    print(f"Different files: {len(differences)}")
    
    if differences:
        print(f"\n{'='*80}")
        print(f"Files with Differences")
        print(f"{'='*80}")
        
        for filename in sorted(differences.keys()):
            xml1, xml2 = differences[filename]
            print(f"\n--- {filename} ---")
            
            if not xml1:
                print("  Status: MISSING in File 1 (Reference)")
            elif not xml2:
                print("  Status: MISSING in File 2 (ppt-rs)")
            else:
                # Show line-by-line diff
                lines1 = xml1.splitlines(keepends=True)
                lines2 = xml2.splitlines(keepends=True)
                diff = difflib.unified_diff(lines1, lines2, lineterm='', n=1)
                diff_lines = list(diff)
                
                if diff_lines:
                    print(f"  Differences ({len(diff_lines)} lines):")
                    for i, line in enumerate(diff_lines[:15]):  # Show first 15 lines
                        print(f"    {line.rstrip()}")
                    if len(diff_lines) > 15:
                        print(f"    ... and {len(diff_lines) - 15} more lines")
    else:
        print("\n✓ All XML files match perfectly!")
    
    # Check file sizes
    print(f"\n{'='*80}")
    print(f"File Sizes")
    print(f"{'='*80}")
    size1 = Path(file1_path).stat().st_size
    size2 = Path(file2_path).stat().st_size
    print(f"File 1 (Reference): {size1:,} bytes")
    print(f"File 2 (ppt-rs):    {size2:,} bytes")
    print(f"Difference:         {abs(size1 - size2):,} bytes ({abs(size1 - size2) / max(size1, size2) * 100:.1f}%)")
    
    # Check ZIP structure
    print(f"\n{'='*80}")
    print(f"ZIP Structure")
    print(f"{'='*80}")
    
    with zipfile.ZipFile(file1_path, 'r') as z1:
        files1 = set(z1.namelist())
    with zipfile.ZipFile(file2_path, 'r') as z2:
        files2 = set(z2.namelist())
    
    only_in_1 = files1 - files2
    only_in_2 = files2 - files1
    
    if only_in_1:
        print(f"\nOnly in File 1 (Reference): {len(only_in_1)} files")
        for f in sorted(only_in_1)[:5]:
            print(f"  - {f}")
        if len(only_in_1) > 5:
            print(f"  ... and {len(only_in_1) - 5} more")
    
    if only_in_2:
        print(f"\nOnly in File 2 (ppt-rs): {len(only_in_2)} files")
        for f in sorted(only_in_2)[:5]:
            print(f"  - {f}")
        if len(only_in_2) > 5:
            print(f"  ... and {len(only_in_2) - 5} more")
    
    if not only_in_1 and not only_in_2:
        print("\n✓ ZIP structure matches perfectly!")
    
    # Summary
    print(f"\n{'='*80}")
    print(f"Summary")
    print(f"{'='*80}")
    
    if len(differences) == 0 and len(only_in_1) == 0 and len(only_in_2) == 0:
        print("✓ Files are IDENTICAL - Perfect alignment!")
        return True
    elif len(differences) <= 5 and len(only_in_1) == 0 and len(only_in_2) == 0:
        print("✓ Files are VERY SIMILAR - Minor differences only")
        return True
    elif len(differences) <= 10:
        print("✓ Files are SIMILAR - Good alignment")
        return True
    else:
        print("⚠ Files have SIGNIFICANT differences")
        return False

if __name__ == "__main__":
    file1 = "examples/output/reference_python_pptx.pptx"
    file2 = "examples/output/enhanced_alignment_ppt_rs.pptx"
    
    if not Path(file1).exists():
        print(f"Error: {file1} not found")
        print("Run: python3 generate_reference.py")
        sys.exit(1)
    
    if not Path(file2).exists():
        print(f"Error: {file2} not found")
        print("Run: cargo run --example enhanced_alignment")
        sys.exit(1)
    
    success = compare_files(file1, file2)
    sys.exit(0 if success else 1)
