#!/usr/bin/env python3
"""
Generate a reference PPTX file using python-pptx for comparison.
This helps us understand the exact structure python-pptx creates.
"""

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
import os

def create_reference_presentation():
    """Create a comprehensive reference presentation"""
    
    # Create presentation
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(7.5)
    
    # Slide 1: Title slide
    slide1 = prs.slides.add_slide(prs.slide_layouts[0])
    title = slide1.shapes.title
    subtitle = slide1.placeholders[1]
    
    title.text = "Reference Presentation"
    subtitle.text = "Generated by python-pptx"
    
    # Slide 2: Content slide with text
    slide2 = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide2.shapes.title
    content = slide2.placeholders[1]
    
    title.text = "Content Slide"
    tf = content.text_frame
    tf.text = "This is a reference presentation"
    
    p = tf.add_paragraph()
    p.text = "Created with python-pptx"
    p.level = 1
    
    # Slide 3: Slide with shape
    slide3 = prs.slides.add_slide(prs.slide_layouts[6])  # Blank layout
    title = slide3.shapes.add_textbox(Inches(0.5), Inches(0.5), Inches(9), Inches(1))
    title_frame = title.text_frame
    title_frame.text = "Shapes Slide"
    
    # Add a shape
    shape = slide3.shapes.add_shape(
        1,  # Rectangle
        Inches(1), Inches(2),
        Inches(3), Inches(2)
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = RGBColor(0, 112, 192)
    shape.line.color.rgb = RGBColor(0, 0, 0)
    
    # Add text to shape
    shape.text = "Shape"
    shape.text_frame.paragraphs[0].font.size = Pt(24)
    shape.text_frame.paragraphs[0].font.bold = True
    shape.text_frame.paragraphs[0].font.color.rgb = RGBColor(255, 255, 255)
    
    # Save presentation
    output_dir = '/Users/yingkitw/Desktop/myproject/ppt-rs/examples/output'
    os.makedirs(output_dir, exist_ok=True)
    
    ref_file = os.path.join(output_dir, 'reference_pptx.pptx')
    prs.save(ref_file)
    
    print(f"✓ Reference presentation created: {ref_file}")
    print(f"✓ File size: {os.path.getsize(ref_file)} bytes")
    print(f"✓ Slides: {len(prs.slides)}")
    
    return ref_file

if __name__ == '__main__':
    create_reference_presentation()
